version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify the Node.js version you're using
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip dist

  post_build:
    commands:
      - echo Build completed on `date`
      - aws lambda update-function-code --function-name metha-ai-utils-nodejs --zip-file fileb://deployment_package.zip
      - echo "DONE!"

artifacts:
  files:
    - '**/*'  # Include all files
  name: metha-ai-utils-nodejs-$(date +%Y-%m-%d-%H-%M-%S).zip  # Name of the zip file
  discard-paths: no