version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify the Node.js version you're using
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  # Include all files
  name: metha-ai-utils-nodejs-$(date +%Y-%m-%d-%H-%M-%S).zip  # Name of the zip file
  discard-paths: no